Repository nextcloud/app-tutorial, pull requests merged in 2022-01, with the labels that each got.

#362 Change webpack config for more platform independency
  package.json
  webpack.config.js
Labels: dependencies, 3. to review

#378 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#379 Updating fixup.yml workflow from template
  .github/workflows/fixup.yml
Labels: dependencies

#373 Split and create standard phpunit actions + summary
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
  phpunit.integration.xml
  phpunit.xml
  tests/phpunit.integration.xml
  tests/phpunit.xml
Labels: enhancement, 3. to review
